import './globals.css';
import { Navigation } from '@/components/Navigation';'../components/Navigation'
import { Footer } from '@/components/Footer';

export const metadata = {
  title: 'PracticasUAM',
  description: 'Generated by create next app',
  keywords: 'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className='header__container'>
          <h1 className='header__title'>PracticasUAM</h1>
          <Navigation />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
